apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-exp-app
spec:
  selector:
    matchLabels:
      app: products
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: products
        department: sales
    spec:
      containers:
        - name: hello
          image: "gcr.io/sample-254915/expressdemo:v1"
          env:
            - name: "PORT"
              value: "8000"
