apiVersion: v1
kind: Service
metadata:
  name: exp-lb-service
spec:
  type: LoadBalancer
  selector:
    app: products
    department: sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
